show_bugs:
  type: bool
  default: true
  description: 'Show bugs on screen!'
        
max_number_fruit_flies:
  type: integer
  default: 10
  min: 0
  max: 100
  description: 'The maximum number of fruit flies to display (0-100)'
  
max_number_spiders:
  type: integer
  default: 2
  min: 0
  max: 100
  description: 'The maximum number of spiders to display (0-100)' 
  
bugs_can_interact:
  type: bool
  default: true
  description: 'Flies will avoid the spiders'

delay_start:
  type: integer
  default: 500
  description: 'Time before the first bug appears in milliseconds.'
  
mouseover_action:
  type: enum
  default: random
  choices:
    - random  
    - fly
    - flyoff
    - die
    - multiply
  description: 'What happens to the bugs when you swat the bugs with your mouse or finger.'  
  
show_for_users:
  type: list
  default: 'admins' 
  description: 'Control who can see the bugs<br>Enter a list of usernames to show to specific users<br>Enter group names to show to specific groups<br>Enter "everyone" to show to all.'

